package com.dietai.dietai.model;

public enum Goal {
    BUILD_MUSCLE_MASS,
    INCREASE_STRENGTH_ENDURANCE,
    IMPROVE_CARDIOVASCULAR_FITNESS,
    LOSE_WEIGHT_REDUCE_BODY_FAT,
    ENHANCE_FLEXIBILITY_MOBILITY,
    IMPROVE_OVERALL_HEALTH_WELLBEING,
    TRAIN_FOR_SPECIFIC_SPORT_EVENT,
    REHABILITATE_FROM_INJURY_MEDICAL_CONDITION,
    BOOST_ENERGY_LEVELS_REDUCE_STRESS,
    ACHIEVE_SPECIFIC_AESTHETIC_PHYSIQUE_GOAL
}
